### ISSUE TITLE
code error in compare.ipynb

### ISSUE THREAD

**Issue by shiqingzhangCSU** [williamgilpin/fnn#5]
1.  ICA code does not work well, something happen but i dont know what it is.
![image](https://user-images.githubusercontent.com/44834482/112784642-c596a880-9084-11eb-8742-969abbfb6cdd.png)

2. model. py
I guess it should be p not q
![image](https://user-images.githubusercontent.com/44834482/112782958-caf1f400-9080-11eb-8fba-9eb84329efc0.png)

**Comment by shiqingzhangCSU** [comment]
I am very grateful if you could reply me ！Thankx！！

**Comment by williamgilpin** [comment]
Thank you! This might be a bug from when I re-factored the Hankel matrix calculation. I will push an update soon, but here is what that line should be instead

`        X_test = hankel_matrix(standardize_ts(X), self.time_window)`

**Comment by williamgilpin** [comment]
Hello, I just pushed a small update fixing this line. Thanks very much for catching this

**Comment by shiqingzhangCSU** [comment]
Hello！ Thank you for  your quick reply！ Now i am compute the homology similarity between different embedding，but the result seems not the same as your paper metioned. Could you please help me to see if there is a problem with my code? Is there a problem when calculating the empty PD?
![image](https://user-images.githubusercontent.com/44834482/112838433-a113ee00-90cf-11eb-85d5-4f693a8f1808.png)
`import persim
import ripser


dgm_org = ripser.ripser(sol.T)['dgms'][1]
dgm_lstm = ripser.ripser(coords_lstm)['dgms'][1]
dgm_mlp = ripser.ripser(coords_mlp)['dgms'][1]
dgm_ica = ripser.ripser(coords_ica)['dgms'][1]
dgm_tica = ripser.ripser(coords_tica)['dgms'][1]
dgm_etd = ripser.ripser(coords_etd)['dgms'][1]
dgm_ami = ripser.ripser(coords_ami)['dgms'][1]
dgm_0 = np.array([[0.0, 0]])
W_0 = persim.wasserstein(dgm_org, dgm_0)
W_lstm1 = persim.wasserstein(dgm_org, dgm_lstm)
W_mlp1 = persim.wasserstein(dgm_org, dgm_mlp)
W_ica1 = persim.wasserstein(dgm_org, dgm_ica)
W_tica1 = persim.wasserstein(dgm_org, dgm_tica)
W_etd1 = persim.wasserstein(dgm_org, dgm_etd)
W_ami1 = persim.wasserstein(dgm_org, dgm_ami)

s_lstm1 = 1-(W_lstm1/W_0)
s_mlp1 = 1-(W_mlp1/W_0)
s_ica1 = 1-(W_ica1/W_0)
s_tica1 = 1-(W_tica1/W_0)
s_etd1 = 1-(W_etd1/W_0)
s_ami1 = 1-(W_ami1/W_0)

print(s_lstm1,s_mlp1,s_ica1,s_tica1,s_etd1,s_ami1)
print(W_lstm1,W_mlp1,W_ica1,W_tica1,W_etd1,W_ami1)`

**Comment by shiqingzhangCSU** [comment]
By the way，how to create a “null” diagram？ 
![image](https://user-images.githubusercontent.com/44834482/112928757-c6ddd900-9149-11eb-8437-a78b33614e94.png)
Thanks！！

**Comment by williamgilpin** [comment]
Hi!  null attractor is just N copies of a D dimensional point. For example, multiply all of the points in \hat{Y} times zero.

**Comment by shiqingzhangCSU** [comment]
Hi！Thanks for your explanation， but I still have some problem in zero attractor？Please look at the code below：

![image](https://user-images.githubusercontent.com/44834482/112983932-d5031800-9190-11eb-80e8-6e8b71ef3dd2.png)
![image](https://user-images.githubusercontent.com/44834482/112983990-e2b89d80-9190-11eb-94bc-d007b9aae916.png)
d_lstm_0 = persim.wasserstein(dgm_org, dgm_lstm_0)
 It seems like d_lstm_0 is zero（![image](https://user-images.githubusercontent.com/44834482/112984096-067be380-9191-11eb-83da-91472e3306ee.png)）
Maybe I cant fliration like this dgm_lstm_0 = ripser.ripser(coords_lstm*0)['dgms'][1] ？

**Comment by shiqingzhangCSU** [comment]
Hi！I tried many ways, but I think what I tried was wrong. Could you please tell me how to normalize the W distance? or tell me how to create a “null” diagram with no salient topological features?
